### PR TITLE
Make proposer duties ssz serializable

### PR DESCRIPTION
**Pull request by mpetrunic**
We cannot ssz serialize map with dynamic keys hence return proposer duties as array of "containers" with static keys

### CODE REVIEW

**Comment by djrtwo** [comment]
What's the status on this PR? Still want review?

**Comment by mpetrunic** [comment]
> What's the status on this PR? Still want review?

I'll update it, that is format in new proposal anyways.

**Comment by mpetrunic** [comment]
This will be inside PR to update validator duties so closing for now

**Comment by djrtwo** [comment]
was just about to ask. thanks!

**Pull request closed without merging**
