### PR TITLE
Update swagger-cli action

### LINKED ISSUE #38: build failed
@mpetrunic @decanus 
new build failed on master... 
I can look into it in a bit, but if either of you have a quick fix, go for it

### PR DESCRIPTION
**Pull request by mpetrunic**
resolves #38 

@djrtwo Can you protect master that it requires PR ci to pass?

### CODE REVIEW

**Comment by decanus** [comment]
@djrtwo now it worked! and apparently the api wasn't right all along :P

**Comment by mpetrunic** [comment]
Uh, this is quite stricter linter. Think previous was just validating if it's valid for swagger-ui :smile:

**Comment by decanus** [comment]
@mpetrunic I guess we could either fix it or try loosen the linter?

**Comment by mpetrunic** [comment]
> @mpetrunic I guess we could either fix it or try loosen the linter?

I will try to fix it, seems like simple errors

**Comment by mpetrunic** [comment]
We should probably fix those warnings along the way^^

**Comment by mpetrunic** [comment]
@djrtwo This is ready to be merged

**Pull request merged**
